language: rust
matrix:
  allow_failures:
  - rust: nightly
  include:
  - rust: stable
    os: linux
  - rust: stable
    os: osx
  - rust: stable
    os: windows
  - rust: beta
    os: linux
  - rust: beta
    os: osx
  - rust: beta
    os: windows
  - rust: nightly
    os: linux
  - rust: nightly
    os: osx
  - rust: nightly
    os: windows
  - env: DEPLOY=1
    rust: stable
    os: osx
    script:
    - cargo make --no-workspace zip-release-ci-flow --env CARGO_MAKE_RELEASE_FLOW_TARGET=x86_64-apple-darwin
  - env: DEPLOY=1
    rust: stable
    os: windows
    before_script:
    - rustup target add x86_64-pc-windows-msvc
    - cargo install --debug cargo-make
    script:
    - cargo make --no-workspace zip-release-ci-flow --env CARGO_MAKE_RELEASE_FLOW_TARGET=x86_64-pc-windows-msvc
  - env: DEPLOY=1
    rust: stable
    os: linux
    script:
    - cargo make --no-workspace zip-release-ci-flow --env CARGO_MAKE_RELEASE_FLOW_TARGET=x86_64-unknown-linux-musl
    addons:
      apt:
        packages:
        - musl-tools
before_script:
- cargo install --debug cargo-make
script:
- cargo make --no-workspace workspace-ci-flow
deploy:
  provider: releases
  api_key:
    secure: XquK9EB1DJ1BsCjqxVuPiUe89lrp8FJtGHZ+iCgwpG504w5muAPoWsM+oNe1S3gbR14SnxwgHfowITceM/oe8Q72SoQ98jKVXEyZGcpSgFbr9Vr16PpWGCP3mRNjqGoY0nguFjm4srgOSMykpaT45YK+Y3Pty8vaOnd4TLa8etxLREt7QD3nm2043/85tRlTf0QIQHI+L+Xbj2Peey4HV3uYs3SGYi4lAuk6fVakcSLQQCNCLgR2l7rhlELInKoTIHTIC91phlfeHK/wJSuTtw8X0TrvR35BxmpxKnXZm7dJPX3Ve03Lee4RPe75tUTpbPLHYML0JM3P3JyTmsRRENYJwvHvkTXGIQTfzNXr2zpNjBqFcURU3UU6YySH6xyqHkrc6qhHnvIABGWG7a3GnrN/qrW4cAFtXx5jIjFBZcVqQOAr6WtLwfyldidap1y253IjdINB5STNQ9Yco9Oq81SN+KMcmakcWgq90rCaE/mNLiHdPQGIxyTtC31EvvnzViwyCXX8/9reeuQEiVz0rD/E80CkrswVR6E+KMnNpVcjaiYthuYP/+D8PirX5oJ+FbX3n+R1WCVuraTtVXjaEqt1csbqBDudfqPPeoZPwKbANdCu3NE0yTpzhqI7CtCuHBmkA6GpjTd3AV35MZ2QasHhphefrwDMzMgzp4LnpTc=
  file_glob: true
  file: "*.zip"
  on:
    condition: $DEPLOY = 1
    tags: true
  skip_cleanup: true
  overwrite: true
