
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

[env.sdk]
CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = "duckscript_sdk;duckscript_cli"

[config]
main_project_member = "duckscript_cli"
additional_profiles = [
    "ci-coverage-tasks",
    "ci-all-build-tasks",
    "publish-pre-cleanup"
]

[tasks.generate-sdk-docs]
workspace = false
script = ["pwd"]
command2 = "cargo"
args2 = [ "run", "--bin", "duckscript", "--", "./sdkdocs.ds", ]

[tasks.generate-readme]
script = [
'''
echo "generating readme file"
rm -f ./README.md
cat ./docs/_includes/README.md ./docs/_includes/nav.md ./docs/_includes/content.md >> README.md
sed -i 's,https://github.com/sagiegurari/duckscript/blob/master/.github,.github,g' ./README.md
'''
]

[tasks.workspace-docs]
dependencies = [
    "generate-sdk-docs",
    "generate-readme"
]

[tasks.install_local]
workspace = false
cwd = "./duckscript_cli"
command = "cargo"
args = [ "install", "--force", "--path", "." ]
