[package]
name = "duckscriptsdk"
version = "0.3.0"
authors = ["Sagie Gur-Ari <sagiegurari@gmail.com>"]
description = "The duckscript SDK."
license = "Apache-2.0"
edition = "2018"
documentation = "https://sagiegurari.github.io/duckscript/api/duckscript/index.html"
homepage = "http://github.com/sagiegurari/duckscript"
repository = "https://github.com/sagiegurari/duckscript.git"
readme = "README.md"
keywords = ["script", "script-engine", "language"]
categories = ["command-line-utilities", "development-tools"]
include = [
    "/benches/*",
    "/docs/*",
    "/examples/*",
    "/src/*",
    "/tests/*",
    "/Cargo.toml",
    "/LICENSE",
    "/README.md"
]

[dependencies]
attohttpc = "^0.12"
base64 = "^0.12"
cfg-if = "^0.1"
duckscript = { version = "^0.3", path = "../duckscript" }
fs_extra = "^1"
fsio = { version = "^0.1", features = ["temp-path"] }
glob = "^0.3"
home = "^0.5"
java-properties = "^1"
meval = "^0.2"
rand = "^0.7"
walkdir = "^2"
whoami = "^0.8"

[target.'cfg(not(windows))'.dependencies]
uname = "^0.1"

[badges.travis-ci]
branch = "master"
repository = "sagiegurari/duckscript"

[badges.appveyor]
repository = "sagiegurari/duckscript"
service = "github"
branch = "master"
project_name = "sagiegurari/duckscript"

[badges.codecov]
branch = "master"
repository = "sagiegurari/duckscript"
service = "github"
