
[config]
additional_profiles = [
    "none-thread-safe-tests",
    "ci-coverage-tasks",
    "ci-all-build-tasks",
    "publish-pre-cleanup"
]

[tasks.clean-target]
condition = { files_exist = ["./target"] }
script_runner = "@duckscript"
script = [
    "rm -Rf ./target"
]

[tasks.test-verbose]
alias = "test"

[tasks.test]
clear = true
dependencies = [
    "clean-target"
]
run_task = { name = ["test-thread-safe", "test-single-threaded", "test-scripts"] }

[tasks.test-thread-safe]
private = true
env = { RUST_TEST_THREADS = { unset = true } }
command = "cargo"
args = ["test"]

[tasks.test-single-threaded]
private = true
env = { RUST_TEST_THREADS = "1" }
command = "cargo"
args = ["test", "--", "--ignored"]

[tasks.test-scripts]
cwd = ".."
command = "cargo"
args = [
    "make",
    "--no-workspace",
    "test-scripts"
]

[tasks.pre-coverage]
alias = "clean-target"
